# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85cb3f1d2c56cd95446e6a8c35f71aadd2dc61c96cdfdf762f2a244620a6f42bfb915d5d89646a3132c203f64f52925224bc2ea7a6063c80150275838c775a66

test:
  secret_key_base: bec8bc55d94deb49fa93afdf849e2fb111236cd43379e00f6399f77d25e431a3e7baa05de5e4311e3fb29521a9684e0c6e96627084f9fa51bc60bc85319e58ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
